loop:
  gain: 0.1
  leakyGain: 0.01
  numDroppedModes: 0
  pokeAmp: 0.000001 #1000nm
  numItersIM: 1
  affinity: 2
  method: push-pull
  functions:
  - leakyIntegrator

wfs:
  name: OOPAOWFS
  width: 28
  height: 28
  darkCount: 1000
  integration: 50
  affinity: 3
  functions:
  - expose

slopes:
  type: PYWFS
  signalType: slopes
  affinity: 4
  flatNorm: True
  #Specify where the pupils are and how large for a PYWFS
  # pupilsRadius: 12
  # pupils:  
  # - 12,12
  # - 36,12
  # - 12,36
  # - 36,36
  functions:
  - computeSignal

wfc:
  name: "OOPAOWFC"
  numActuators: 100
  numModes: 80
  flatFile: ""
  saveFile: "flat.npy"
  m2cFile:  ""
  affinity: 3
  commandCap: 0.8
  hardwareDelay: 0.001
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "OOPAOPSF"
  index: 0
  width: 200
  height: 200
  darkCount: 10
  integration: 10
  affinity: 3
  functions:
  - expose
  - integrate
  - computeStrehl
