loop:
  gain: 0.1
  leakyGain: 0.01
  numDroppedModes: 0
  pokeAmp: 9.5e-7  # 950 nm
  numItersIM: 1
  affinity: 2
  method: push-pull
  functions:
  - leakyIntegrator

wfs:
  name: OOPAOWFS
  # 25x25 lenslets * 15 px per lenslet = 375 px sensor
  width: 350
  height: 350
  darkCount: 1000
  integration: 50
  affinity: 3
  functions:
  - expose

slopes:
  # Switch to Shack-Hartmann WFS
  type: SHWFS
  signalType: slopes
  affinity: 4
  flatNorm: True

  # SH-WFS geometry
  lensletsX: 25
  lensletsY: 25
  pixelsPerLenslet: 14
  # Optional: define pupil if your sensor has margins; comment out if auto-detected
  # pupilsRadius: 187
  # pupils:
  # - 187,187

  functions:
  - computeSignal

wfc:
  name: "OOPAOWFC"
  numActuators: 97
  numModes: 97
  flatFile: ""
  saveFile: "flat.npy"
  m2cFile: ""
  affinity: 3
  commandCap: 0.8
  hardwareDelay: 0.001
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "OOPAOPSF"
  index: 0
  width: 200
  height: 200
  darkCount: 10
  integration: 10
  wavelengthNm: 950
  affinity: 3
  functions:
  - expose
  - integrate
  - computeStrehl
