loop:
  gain: 0.1
  leaky_gain: 0.0
  num_dropped_modes: 30
  poke_amp: 0.02
  num_iters_im: 50
  affinity: 2
  delay: 2
  method: push-pull
  im_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/IM_PYWFS.npy"
  p_gain: 0.28
  i_gain: 0.066
  d_gain: 0.078
  control_limits: [-0.05, 0.05]
  absolute_limits: [-0.3, 0.3]
  integral_limits: [-0.1, 0.1]
  derivative_filter: 0.1
  # gpu_device: 0
  class_name: Loop
  input_streams:
    signal: signal
  output_streams:
    wfc: wfc
  functions:
  - leaky_integrator

  # left: 544
  # top: 100 
  # width: 384 
  # height: 384 

wfs:
  name: XIMEA
  serial: "13056250"
  binning: 2 
  exposure: 3333
  gain: 0
  bit_depth: 10
  left: 240
  top: 50 
  width: 192 
  height: 192 
  dark_count: 2000
  dark_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/darkPyWFS.npy"
  affinity: 3
  # gpu_device: 0
  class_name: XIMEAWFS
  input_streams: {}
  output_streams:
    wfs_raw: wfs_raw
    wfs: wfs
  functions:
  - expose

  # pupils: 
  # - 90,110
  # - 91,270
  # - 300,145
  # - 260,270

slopes:
  type: PYWFS
  signal_type: slopes
  valid_sub_aps_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/validSubApsPyWFS.npy"
  ref_slopes_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/refPyWFS.npy"
  flat_norm: True
  pupils_radius: 32 #64
  # gpu_device: 0
  pupils: 
  - 45,48
  - 46,128
  - 152,65 #140, 60
  - 130,128
  affinity: 4
  class_name: SlopesProcess
  input_streams:
    wfs: wfs
  output_streams:
    signal: signal
    signal_2d: signal_2d
  functions:
  - compute_signal

wfc:
  name: "ALPAO"
  serial: "BAX118"
  num_actuators: 97
  num_modes: 94
  flat_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/wfcShapePyWFS.npy"
  save_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/wfcShapePyWFS.npy"
  m2c_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/m2c_kl.npy" 
  floating_actuators_file: ""
  floating_influence_radius: 1
  affinity: 5
  command_cap: 0.8
  hardware_delay: 0.001 #seconds
  # gpu_device: 0
  frame_delay: 0
  class_name: ALPAODM
  input_streams: {}
  output_streams:
    wfc: wfc
    wfc_2d: wfc_2d
  functions:
  - send_to_hardware

psf:
  name: "FLIR"
  index: 0
  exposure: 800
  gain: 0
  bit_depth: 16
  left: 936
  top: 448
  width: 128
  height: 128
  dark_count: 2000
  dark_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/psfDark_PyWFS.npy"
  model_file: "/home/whetstone/pyrtc/examples/sharp_lab/calib/modelPSF_PyWFS.npy"
  integration: 5000
  affinity: 6
  class_name: SpinnakerScienceCamera
  input_streams: {}
  output_streams:
    psf_short: psf_short
    psf_long: psf_long
    strehl: strehl
    tiptilt: tiptilt
  functions:
  - expose
  - integrate
  - compute_strehl

optimizer:
  ncpa:
    name: "NCPA"
    num_steps: 100
    start_mode: 0
    end_mode: 40
    correction_mag: 0.003
    num_reads: 1
    affinity: 10
  pid:
    name: "PID"
    num_steps: 100
    max_p_gain: 0.5
    max_i_gain: 0.1
    max_d_gain: 0.1
    num_reads: 1
    affinity: 10
  loop:
    name: "hyper"
    num_steps: 100
    min_gain: 0.3
    max_gain: 0.8
    max_leak: 0.05
    max_dropped_modes: 30
    num_reads: 1
    affinity: 10
modulator:
  name: 'E-727'
  class_name: PIModulator
  input_streams: {}
  output_streams: {}
  lib_folder: '/opt/PI/lib64/'
  digital_freq: 20000 #Hz
  frequency: 300 #Hz
  amplitude: 600
  relative_amplitude: 1.0
  offset_x: 2500 #2800
  offset_y: 2500 #1100
  phase_offset: 0
  servos_on: False
  auto_zero: True 
  affinity: 7

manager:
  mode: soft-rtc
  component_classes:
    modulator: pyrtc.hardware.pi_modulator
    wfs: pyrtc.hardware.XIMEAWFS
    slopes: pyrtc.slopes_process.SlopesProcess
    loop: pyrtc.loop.Loop
    wfc: pyrtc.hardware.alpao_dm
    psf: pyrtc.hardware.SpinnakerScienceCamera
  component_files:
    modulator: ../../pyrtc/hardware/pi_modulator.py
    wfs: ../../pyrtc/hardware/ximea_wfs.py
    slopes: ../../pyrtc/slopes_process.py
    loop: ../../pyrtc/loop.py
    wfc: ../../pyrtc/hardware/alpao_dm.py
    psf: ../../pyrtc/hardware/spinnaker_science_cam.py

