[pytest]
testpaths = tests
addopts = -ra --strict-markers --cov=pyRTC.utils --cov=pyRTC.pyRTCComponent --cov=pyRTC.WavefrontCorrector --cov=pyRTC.ScienceCamera --cov=pyRTC.Telemetry --cov=pyRTC.Modulator --cov=pyRTC.Optimizer --cov-report=term-missing --cov-report=xml --cov-fail-under=80
filterwarnings =
	ignore:The NumPy module was reloaded \(imported a second time\).*:UserWarning:matplotlib\.cbook
