wfc:
  name: "SUPERPAOWER"
  # serialPort: "COM10"
  serialPort: "/dev/ttyUSB1"
  baudRate: 115200
  numActuators: 16
  numModes: 16
  communicationPause: 0.05
  # flatFile: "./calib/flat.npy"
  saveFile: "./calib/wfcShape.npy"
  # m2cFile:  "./calib/m2c.npy"
  affinity: 2
  functions:
  - sendToHardware

power:
  name: "powerMeter"
  device: "/dev/usbtmc2"
  width: 1
  height: 1
  exposure: 1 #How many power reads averages per read
  darkCount: 100 #How many reads averages to get background
  integration: 1 #How many reads integrated for psfLong
  imageDType: float32
  # darkFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/psfDark.npy"
  # modelFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/modelPSF.npy"
  affinity: 3
  functions:
  - expose
  - integrate
  # - computeStrehl