specula:
  class_name: pyrtc.hardware.specula_interface.SPECULAInterface
  class_file: ../../pyrtc/hardware/specula_interface.py
  paramFile: pywfs_SPECULA_params.yaml
  wfc_section: wfc
  use_atmosphere: false
  input_streams: {}
  output_streams: {}
loop:
  gain: 0.1
  leaky_gain: 0.01
  num_dropped_modes: 0
  poke_amp: 100
  num_iters_im: 8
  conditioning: 10
  affinity: 2
  method: push-pull
  class_name: Loop
  input_streams:
    signal: signal
  output_streams:
    wfc: wfc
  functions:
  - leaky_integrator
  class_file: ../../pyrtc/loop.py
wfs:
  name: SPECULAWFS
  width: 96
  height: 96
  dark_count: 16
  affinity: 3
  class_name: pyrtc.hardware.specula_interface.SPECULAWFSensor
  resource: specula
  input_streams: {}
  output_streams:
    wfs_raw: wfs_raw
    wfs: wfs
  functions:
  - expose
  class_file: ../../pyrtc/hardware/specula_interface.py
slopes:
  type: PYWFS
  signal_type: slopes
  affinity: 4
  flat_norm: true
  class_name: SlopesProcess
  input_streams:
    wfs: wfs
  output_streams:
    signal: signal
    signal_2d: signal_2d
  functions:
  - compute_signal
  class_file: ../../pyrtc/slopes_process.py
wfc:
  name: SPECULADM
  num_actuators: 400
  num_modes: 54
  flat_file: ''
  save_file: specula_flat.npy
  m2c_file: ''
  affinity: 3
  hardware_delay: 0.001
  frame_delay: 0
  class_name: pyrtc.hardware.specula_interface.SPECULAWFCorrector
  resource: specula
  input_streams:
    wfc: wfc
  output_streams:
    wfc: wfc
    wfc_2d: wfc_2d
  functions:
  - send_to_hardware
  class_file: ../../pyrtc/hardware/specula_interface.py
psf:
  name: SPECULAPSF
  width: 160
  height: 160
  dark_count: 1
  integration: 4
  affinity: 5
  class_name: pyrtc.hardware.specula_interface.SPECULAScienceCamera
  resource: specula
  input_streams: {}
  output_streams:
    psf_short: psf_short
    psf_long: psf_long
    strehl: strehl
    tiptilt: tiptilt
  functions:
  - expose
  - integrate
  class_file: ../../pyrtc/hardware/specula_interface.py
manager:
  mode: soft-rtc
  component_classes:
    specula: pyrtc.hardware.specula_interface.SPECULAInterface
    loop: pyrtc.loop.Loop
    wfs: pyrtc.hardware.specula_interface.SPECULAWFSensor
    slopes: pyrtc.slopes_process.SlopesProcess
    wfc: pyrtc.hardware.specula_interface.SPECULAWFCorrector
    psf: pyrtc.hardware.specula_interface.SPECULAScienceCamera
  component_files:
    specula: ../../pyrtc/hardware/specula_interface.py
    loop: ../../pyrtc/loop.py
    wfs: ../../pyrtc/hardware/specula_interface.py
    slopes: ../../pyrtc/slopes_process.py
    wfc: ../../pyrtc/hardware/specula_interface.py
    psf: ../../pyrtc/hardware/specula_interface.py
  graph_layout:
    positions:
      wfc:
        x: 753.7972500000001
        y: -117.38974999999994
      wfs:
        x: -112.16900000000001
        y: 15.562625000000011
      slopes:
        x: 184.66199999999998
        y: -101.62824999999998
      loop:
        x: 480.8071249999999
        y: 48.646125
      psf:
        x: 57.11725000000001
        y: 256.08349999999996
      specula:
        x: 482.8926250000002
        y: 257.60437500000006
metadata: {}
streams: {}
resources: {}
