oopao:
  class_name: pyrtc.hardware.oopao_interface.OOPAOInterface
  class_file: ../../pyrtc/hardware/oopao_interface.py
  paramFile: pywfs_OOPAO_params.yaml
  wfc_section: wfc
  use_atmosphere: false
  input_streams: {}
  output_streams: {}
loop:
  gain: 0.1
  leaky_gain: 0.01
  num_dropped_modes: 0
  poke_amp: 1.0e-07
  num_iters_im: 10
  conditioning: 10
  affinity: 2
  method: push-pull
  class_name: Loop
  input_streams:
    signal: signal
  output_streams:
    wfc: wfc
  functions:
  - leaky_integrator
  class_file: ../../pyrtc/loop.py
wfs:
  name: OOPAOWFS
  width: 48
  height: 48
  dark_count: 1000
  affinity: 3
  class_name: pyrtc.hardware.oopao_interface.OOPAOWFSensor
  resource: oopao
  input_streams: {}
  output_streams:
    wfs_raw: wfs_raw
    wfs: wfs
  functions:
  - expose
  class_file: ../../pyrtc/hardware/oopao_interface.py
slopes:
  type: PYWFS
  signal_type: slopes
  affinity: 4
  flat_norm: true
  class_name: SlopesProcess
  input_streams:
    wfs: wfs
  output_streams:
    signal: signal
    signal_2d: signal_2d
  functions:
  - compute_signal
  class_file: ../../pyrtc/slopes_process.py
wfc:
  name: OOPAOWFC
  num_actuators: 441
  num_modes: 80
  flat_file: ''
  save_file: flat.npy
  m2c_file: ''
  affinity: 3
  command_cap: 0.8
  hardware_delay: 0.001
  frame_delay: 0
  class_name: pyrtc.hardware.oopao_interface.OOPAOWFCorrector
  resource: oopao
  input_streams:
    wfc: wfc
  output_streams:
    wfc: wfc
    wfc_2d: wfc_2d
  functions:
  - send_to_hardware
  class_file: ../../pyrtc/hardware/oopao_interface.py
psf:
  name: OOPAOPSF
  index: 0
  width: 200
  height: 200
  dark_count: 10
  integration: 5
  affinity: 3
  class_name: pyrtc.hardware.oopao_interface.OOPAOScienceCamera
  resource: oopao
  input_streams: {}
  output_streams:
    psf_short: psf_short
    psf_long: psf_long
    strehl: strehl
    tiptilt: tiptilt
  functions:
  - expose
  - integrate
  class_file: ../../pyrtc/hardware/oopao_interface.py
manager:
  mode: soft-rtc
  component_classes:
    oopao: pyrtc.hardware.oopao_interface.OOPAOInterface
    loop: pyrtc.loop.Loop
    wfs: pyrtc.hardware.oopao_interface.OOPAOWFSensor
    slopes: pyrtc.slopes_process.SlopesProcess
    wfc: pyrtc.hardware.oopao_interface.OOPAOWFCorrector
    psf: pyrtc.hardware.oopao_interface.OOPAOScienceCamera
  component_files:
    oopao: ../../pyrtc/hardware/oopao_interface.py
    loop: ../../pyrtc/loop.py
    wfs: ../../pyrtc/hardware/oopao_interface.py
    slopes: ../../pyrtc/slopes_process.py
    wfc: ../../pyrtc/hardware/oopao_interface.py
    psf: ../../pyrtc/hardware/oopao_interface.py
  graph_layout:
    positions:
      oopao:
        x: 142.41983331640614
        y: 424.21956642421856
      wfc:
        x: 1021.9363610453123
        y: 235.23111875000006
      wfs:
        x: -18.0
        y: -48.20329374999997
      slopes:
        x: 282.23906875
        y: 188.1436687499999
      psf:
        x: 568.4230562499997
        y: 412.17546874999994
      loop:
        x: 588.0280210757815
        y: -34.74503125
metadata: {}
streams: {}
resources: {}
