loop:
  gain: 0.1
  leakyGain: 0.0
  numDroppedModes: 30
  pokeAmp: 0.02
  numItersIM: 50
  affinity: 2
  delay: 2
  method: push-pull
  IMFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/IM_PYWFS.npy"
  pGain: 0.28
  iGain: 0.066
  dGain: 0.078
  controlLimits: [-0.05, 0.05]
  absoluteLimits: [-0.3, 0.3]
  integralLimits: [-0.1, 0.1]
  derivativeFilter: 0.1
  functions:
  - leakyIntegrator

  # left: 544
  # top: 100 
  # width: 384 
  # height: 384 

wfs:
  name: XIMEA
  serial: "13056250"
  binning: 2 
  exposure: 3333
  gain: 0
  bitDepth: 10
  left: 272
  top: 50 
  width: 192 
  height: 192 
  darkCount: 2000
  darkFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/darkPyWFS.npy"
  affinity: 3
  functions:
  - expose

  # pupils: 
  # - 90,110
  # - 91,270
  # - 300,145
  # - 260,270

slopes:
  type: PYWFS
  signalType: slopes
  validSubApsFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/validSubApsPyWFS.npy"
  refSlopesFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/refPyWFS.npy"
  flatNorm: True
  pupilsRadius: 32 #64
  pupils: 
  - 45,55
  - 46,135
  - 150,72
  - 130,135
  affinity: 4
  functions:
  - computeSignal

wfc:
  name: "ALPAO"
  serial: "BAX118"
  numActuators: 97
  numModes: 94
  flatFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/wfcShape.npy"
  saveFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/wfcShape.npy"
  m2cFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/m2c_kl.npy" 
  floatingActuatorsFile: ""
  floatingInfluenceRadius: 1
  affinity: 5
  commandCap: 0.8
  hardwareDelay: 0.001 #seconds
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "FLIR"
  index: 0
  exposure: 800
  gain: 0
  bitDepth: 16
  left: 920
  top: 468
  width: 128
  height: 128
  darkCount: 2000
  darkFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/psfDark_PyWFS.npy"
  modelFile: "/home/whetstone/pyRTC/SHARP_LAB/calib/modelPSF_PyWFS.npy"
  integration: 5000
  affinity: 6
  functions:
  - expose
  - integrate
  - computeStrehl

optimizer:
  ncpa:
    name: "NCPA"
    numSteps: 100
    startMode: 0
    endMode: 40
    correctionMag: 0.003
    numReads: 1
    affinity: 10
  pid:
    name: "PID"
    numSteps: 100
    maxPGain: 0.5
    maxIGain: 0.1
    maxDGain: 0.1
    numReads: 1
    affinity: 10

modulator:
  name: 'E-727'
  libFolder: '/opt/PI/lib64/'
  digitalFreq: 20000 #Hz
  frequency: 300 #Hz
  amplitude: 2000
  relativeAmplitude: 1
  offsetX: 2500 #2800
  offsetY: 2500 #1100
  phaseOffset: 0
  servosOn: False
  autoZero: True 
  affinity: 7

