loop:
  gain: 0.1
  leakyGain: 0
  numDroppedModes: 0
  pokeAmp: 0.02
  numItersIM: 50
  affinity: 18
  delay: 1 #delay for docrime
  method: docrime
  IMFile: "" #"/home/jtaylor/pyRTC/MAPS/calib/IM.npy"
  pGain: 0.316
  iGain: 0.0612
  dGain: 0.0481
  controlLimits: [-0.1, 0.1]
  integralLimits: [-0.1, 0.1]
  derivativeFilter: 0.1
  functions:
  - pidIntegrator

wfs:
  name: IRWFS
  isioShmName: irwfs_raw
  left: 0 
  top: 0 
  # width: 160 #VISWFS
  # height: 128 #VISWFS
  width: 80 #IRWFS
  height: 80 #IRWFS
  darkCount: 2000
  darkFile: "/etc/chai/dark.fits"
  affinity: 19
  functions:
  - expose

slopes:
  type: PYWFS
  signalType: slopes
  flatNorm: True
  centralObscurationRatio: 0.25
  pupilsRadius: 14 #IRWFS
  # pupilsRadius: 18 #VISWFS
  affinity: 20
  # pupils: #VISWFS
  # - 45,56
  # - 45,97
  # - 87,56
  # - 87,96
  pupils: #IRWFS
  - 17,18
  - 17,61
  - 62,18
  - 62,61
  functions:
  - computeSignal

wfc:
  name: "MAPS"
  isioShmName: dm00disp
  numActuators: 336
  numModes: 20
  flatFile: "" #"/home/jtaylor/pyRTC/MAPS/calib/wfcShape.npy"
  saveFile: "/home/jtaylor/pyRTC/MAPS/calib/wfcShape.npy"
  m2cFile: "/home/jtaylor/pyRTC/MAPS/calib/m2c_zern_20.npy" 
  actMap: "/home/jtaylor/pyRTC/MAPS/calib/maps_act_mapping.json"
  floatingActuatorsFile: ""
  floatingInfluenceRadius: 1
  affinity: 21
  hardwareDelay: 0.002 #seconds
  frameDelay: 0
  functions:
  - sendToHardware


optimizer:
  ncpa:
    name: "NCPA"
    numSteps: 100
    startMode: 0
    endMode: 20
    correctionMag: 0.003
    numReads: 1
    affinity: 10
  pid:
    name: "PID"
    numSteps: 100
    maxPGain: 0.5
    maxIGain: 0.1
    maxDGain: 0.1
    numReads: 1
    affinity: 10

